import React, { Component } from 'react'

export default class FooterLink extends Component {
  render() {
    return (
      <div className="bg-white border-t-2 border-grey-lighter pl-6 pr-6"><div className="container mx-auto py-6 my-6"><div className="flex flex-col sm:flex-col md:flex-row xl:flex-row text-black"><div className="flex-1 mr-6"><a href=""><svg version="1.2" baseProfile="tiny" id="Layer_1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" viewBox="0 0 18 18" width="32" height="32" ><path id="XMLID_391_" fill="#F05A28" d="M10.5,5.6l6.6,5.3c0.8,0.6,1.1,1.6,0.8,2.6l-1.2,4.1c-1.1,3.3-4.1-17.4-7.6-17.4h0 c-3.5,0-6.6,20.7-7.7,17.3l-1.3-4.1c-0.3-0.9,0-1.8,0.8-2.3l6.9-5.5C8.5,5,9.6,5,10.5,5.6z"></path></svg></a> <span className="text-3xl font-bold">Adamusik</span> <div className="font-sans text-sm pt-3 text-grey-darker text-sm tracking-wide leading-normal">
                    Jelajahi acara musik, band, musisi dan dapatkan kesempatan ikut serta dalam acara musik dimanapun sesuai genre musikmu.
                </div></div> <div className="flex-grow"><div className="flex font-sans text-sm md:text-base"><div className="w-1/3"><h4 className="py-4 text-black">Adamusik</h4> <ul className="list-reset text-grey-darker"><li className="py-2"><a href="#" className="text-orange-dark hover:text-orange no-underline">Tentang Kami</a></li> <li className="py-2"><a href="#" className="text-orange-dark hover:text-orange no-underline">Syarat &amp; Ketentuan</a></li> <li className="py-2"><a href="#" className="text-orange-dark hover:text-orange no-underline">Kebijakan Privasi</a></li></ul></div> <div className="w-1/3"><h4 className="py-4 text-black">Bantuan</h4> <ul className="list-reset text-grey-darker"><li className="py-2"><a href="#" className="text-orange-dark hover:text-orange no-underline">Cara Kerja</a></li> <li className="py-2"><a href="#" className="text-orange-dark hover:text-orange no-underline">FAQ</a></li> <li className="py-2"><a href="#" className="text-orange-dark hover:text-orange no-underline">Kontak</a></li></ul></div> <div className="w-1/2"><h4 className="py-4 text-black">Ikuti Adamusik Disini</h4> <div className="flex"><span className="mr-6"><a href="https://web.facebook.com/adamusik.id" target="_blank"><i className="fab fa-facebook-square fa-2x text-orange hover:text-orange-dark"></i></a></span> <span className="mr-6"><a href="https://twitter.com/adamusik_id" target="_blank"><i className="fab fa-twitter-square fa-2x text-orange hover:text-orange-dark"></i></a></span> <span className="mr-6"><a href="https://www.instagram.com/adamusik.id" target="_blank"><i className="fab fa-instagram fa-2x text-orange hover:text-orange-dark"></i></a></span></div></div></div></div></div></div></div>
    )
  }
}
